/**
 * WikiText 翻译术语表 — 与 chs.js 游戏汉化保持一致
 */
export const GLOSSARY: Record<string, string> = {
  // === 章节标题 ===
  "Introduction": "简介",
  "Recipe": "配方",
  "Images": "图片",
  "Ability": "技能",
  "Other Info": "其他信息",
  "Extra Info": "额外信息",
  "Layers": "地层",
  "Gears": "齿轮",
  "Pickaxes": "镐子",
  "Pickaxe Stats": "镐子属性",
  "Stats": "属性",
  "Events": "事件",
  "Contents": "目录",
  "Overview": "概述",
  "Trivia": "冷知识",
  "Gallery": "画廊",
  "Notes": "备注",
  "Note": "备注",
  "Tips": "小贴士",
  "Summary": "总结",
  "List": "列表",
  "Details": "详情",
  "Information": "信息",
  "Description": "描述",
  "Appearance": "外观",
  "Obtaining": "获取方式",
  "Usage": "用法",
  "History": "历史",
  "See Also": "参见",
  "References": "参考",
  "Sources": "来源",
  "Related": "相关",

  // === Tier 等级 (对齐 chs.js) ===
  "Layer": "地层",
  "Common": "普通",
  "Uncommon": "罕见",
  "Rare": "稀有",
  "Legendary": "传说",
  "Godly": "神级",
  "Antique": "古董",
  "Mystical": "神秘",
  "Divine": "神圣",
  "Flawless": "无瑕",
  "Interstellar": "星际",
  "Metaversal": "元宇宙",
  "Sacred": "圣洁",
  "Celestial": "天界",
  "Ethereal": "虚灵",
  "Imaginary": "幻象",
  "Polychromatical": "多彩",
  "Hyperdimensional": "超维",
  "Infinitesimal": "无穷小",

  // === 游戏术语 ===
  "pickaxe": "镐子",
  "Pickaxe": "镐子",
  "pickaxes": "镐子",
  "ore": "矿石",
  "Ore": "矿石",
  "ores": "矿石",
  "layer": "地层",
  "Layer": "地层",
  "layers": "地层",
  "gear": "齿轮",
  "Gear": "齿轮",
  "gears": "齿轮",
  "world": "世界",
  "World": "世界",
  "worlds": "世界",
  "ability": "技能",
  "Ability": "技能",
  "luck": "幸运",
  "Luck": "幸运",
  "block": "方块",
  "blocks": "方块",
  "mine": "挖掘",
  "mining": "挖掘",
  "craft": "合成",
  "crafting": "合成",
  "recipe": "配方",
  "spawn": "生成",
  "spawns": "生成",
  "spawned": "已生成",
  "rarity": "稀有度",
  "Rarity": "稀有度",
  "tier": "等级",
  "Tier": "等级",
  "consistency": "一致性",
  "Consistency": "一致性",
  "automine": "自动挖掘",
  "cave": "洞穴",
  "caves": "洞穴",
  "teleport": "传送",
  "profile": "存档",
  "event": "事件",
  "Event": "事件",
  "secret": "隐藏",
  "Secret": "隐藏",
  "special": "特殊",
  "Special": "特殊",
  "normal": "普通",
  "Normal": "普通",
  "repeating": "重复",
  "Repeating": "重复",
  "subrealm": "子领域",
  "Subrealm": "子领域",
  "cave type": "洞穴类型",
  "forge": "锻造",
  "variants": "变体",
  "variant": "变体",
  "milestone": "里程碑",
  "Milestone": "里程碑",

  // === 世界名称 (对齐 chs.js) ===
  "World One": "世界一",
  "World Two": "世界二",
  "Subrealm One": "子领域一",

  // === 常见短语 ===
  "can be found in": "可在以下位置找到：",
  "can be found across all worlds": "可在所有世界中找到",
  "is a pickaxe that can be found in": "是一把可在以下地点找到的镐子：",
  "is the first world you enter inside of": "是你进入的第一个世界",
  "It houses a total of": "它总共包含",
  "It also has a total of": "它还总共有",
  "one of which being": "其中之一是",
  "is the very first place you begin to mine in": "是你开始挖掘的第一个地方",
  "Your journey tends to begin inside of": "你的旅程通常始于",
  "it could begin elsewhere depending on where you choose to start out": "根据你选择的起点，也可能从其他地方开始",
  "The ability mines out": "技能可挖掘出",
  "and mines 3 more blocks to each side of the ability": "并在技能每侧额外挖掘 3 个方块",
  "The ability mines": "该技能可挖掘",
  "while revealing": "同时揭示",
  "the pickaxe has a luck boost of": "该镐子拥有",
  "a 1/50 chance to activate the ability when mining a block": "挖掘方块时有 1/50 概率触发技能",
  "This all comes together to make a pickaxe consistency of": "综合来看，该镐子的一致性为",
  "has a total of": "共有",
  "there are a total of": "共有",
  "The icon for this pickaxe was made by": "该镐子图标由以下作者制作：",
  "in the Silly Caverns Discord": "在 Silly Caverns Discord 中",
  "Used for accessing": "用于进入",
  "Mines 1 blocks, reveals 1 blocks, has 1x luck": "挖掘 1 个方块，揭示 1 个方块，拥有 1 倍幸运",
  "This makes the pickaxe have": "这使得该镐子的一致性为",
  "Mines 2 blocks at once when using automine": "使用自动挖掘时一次挖掘 2 个方块",
  "Has 2x special cave type luck and slightly increased cave size": "拥有 2 倍特殊洞穴类型幸运，洞穴大小略微增加",
  "After this point, once passing 17999m you enter into the Repeating Layers": "在此之后，一旦超过 17999 米，你将进入重复地层",
  "Inside of the Repeating Layers is where you can find the three special layers": "在重复地层中，你可以找到三个特殊地层",
  "All of them can spawn in the Repeating Layers but have a certain set chance of when they can take over a Repeating Layer and turn it into one of themselves": "它们都可以在重复地层中生成，但各自有设定的概率来取代某个重复地层并转变为自身",
  "Here is a little more info on that topic from the In-Game FAQ and Discord": "以下是来自游戏内 FAQ 和 Discord 的更多相关信息：",
  "there is a special ore that is only obtainable once you get the event": "有一种特殊矿石只有在触发事件后才能获得",
  "But, the event is really, REALLY rare and lasts for 2.50 hours": "但该事件极其罕见，持续 2.5 小时",
  "After crafting": "合成后",
  "After this point": "在此之后",
  "once passing": "一旦超过",
  "you enter into": "你将进入",
  "Inside of the Repeating Layers": "在重复地层中",
  "All of them can spawn": "它们都可能生成",
  "have a certain set chance": "有特定的概率",
  "take over a Repeating Layer": "取代一个重复地层",
  "turn it into one of themselves": "将其转变为自身",
  "a little more info": "更多信息",
  "in the Silly Caverns Discord": "在 Silly Caverns Discord",
  "Silly Caverns Discord": "Silly Caverns Discord",
  "Silly Caverns": "Silly Caverns",
  "The icon for this pickaxe was made by": "该镐子的图标作者为",
  "Used for accessing": "用于进入",
  "mined": "已挖",
  "Mines": "挖掘",
  "reveals": "揭示",
  "has a": "拥有",
  "chance to": "概率",
  "ability activation rate": "技能触发概率",
  "makes the pickaxe have": "使该镐子拥有",
  "Mines 2 blocks at once when using automine": "自动挖掘时一次挖掘 2 个方块",
  "Has 2x special cave type luck": "拥有 2 倍特殊洞穴类型幸运",
  "slightly increased cave size": "洞穴大小略微增加",
  "blocks at once": "个方块（一次性）",
  "when using automine": "使用自动挖掘时",
  "special cave type luck": "特殊洞穴类型幸运",
  "cave size": "洞穴大小",
  "slightly increased": "略微增加",
  "consistency": "一致性",
  "1/100000 chance for the event": "事件概率为 1/100000",
  "new profile": "新存档",
  "start out": "开始",
  "begin to mine": "开始挖掘",
  "first place": "第一个地方",
  "houses a total of": "总共包含",
  "special layers": "特殊地层",
  "Normal layers": "普通地层",
  "normal layers": "普通地层",
  "Repeating Layers": "重复地层",
  "repeating layers": "重复地层",
  "special layer": "特殊地层",
  "secret layers": "隐藏地层",
  "inside of": "之中",
  "can be found": "可以找到",
  "is where you can find": "可以找到",
  "Here is a little more info": "以下是更多信息",
  "on that topic": "关于这个主题",
  "from the In-Game FAQ and Discord": "来自游戏内 FAQ 和 Discord",
  "there is a special ore": "有一种特殊矿石",
  "only obtainable once you get the event": "只有在触发事件后才能获得",
  "really, REALLY rare": "极其罕见",
  "lasts for": "持续",

  // === 常见表头 ===
  "Ability Mined": "技能挖掘数",
  "Ability Revealed": "技能揭示数",
  "Ability Activation Rate": "技能触发率",
  "Pickaxe Cons": "镐子一致性",
  "Amount": "数量",
  "Base Rarity": "基础稀有度",
  "Spawn Layer": "生成地层",
  "Spawn Message": "生成消息",
  "Has Spawned": "已生成",

  // === Infobox 参数名 ===
  "pickaxename": "镐子名称",
  "pickaxeicon": "图标",
  "abilityimage": "技能图标",
  "pickaxe tier": "镐子等级",
  "pickaxe_tier": "镐子等级",
  "stats": "属性",
  "pickaxe stats": "镐子属性",
  "extra info": "额外信息",
  "extra_info": "额外信息",

  // === 数值表达 ===
  "1/50": "1/50",
  "1x": "1倍",
  "2x": "2倍",
  "60x": "60倍",
  "Ability Mined.": "技能挖掘数",
  "Ability Revealed.": "技能揭示数",
  "Luck.": "幸运",
  "Ability Activation Rate.": "技能触发率",
  "Pickaxe Cons.": "镐子一致性",

  // === 镐子中文名 (对齐 chs.js) ===
  "Mulch Mallet": "腐土槌",
  "Mud Sickle": "泥浆镰刀",
  "Dirt Ravager": "泥土掠夺者",
  "Crystalline Excavator": "水晶挖掘机",
  "Ballast Breaker": "压舱粉碎者",
  "Tropical Carver": "热带雕刻者",
  "Void Crusher": "虚空粉碎者",
  "Geode Staff": "晶洞法杖",
  "Earth Soiler": "大地污染者",
  "Crypt Smasher": "墓穴粉碎者",
  "Labyrinthian Tide": "迷宫之潮",
  "77 Leaf Destroyer": "77叶毁灭者",
  "Planet Buster": "行星破坏者",
  "Whirlpool of Fate": "命运漩涡",
  "Wings of Glory": "荣耀之翼",
  "The Key": "钥匙",
  "Extreme Echolocator": "极限回声定位器",
  "Corundum Caver": "刚玉洞穴者",
  "Starborne Slasher": "星生斩击者",
  "Nyabomb": "喵炸弹",
  "Lunar Lightsabre": "月光光剑",
  "Gemstone Engraver": "宝石雕刻者",
  "Gambler's Fallacy": "赌徒谬误",
  "Coronary Catastrophe": "冠状动脉灾难",
  "Undersea Eviscerator": "海底剔骨者",
  "Null Chroma": "Null Chroma",
  "Hypermark Checkminator": "Hypermark Checkminator",
  "God of the Mine (GOTM)": "矿洞之神",
  "Omnipotent God of the Mine": "全能矿洞之神",
  "Galactica": "银河",
  "Watr Watr": "水水",
};

/**
 * 翻译纯文本段落（非 WikiText 标记行）
 */
export function translateText(text: string): string {
  let result = text;

  // 先匹配长短语（降序排列避免短词优先匹配）
  const longPhrases = Object.keys(GLOSSARY)
    .filter(k => k.includes(" "))
    .sort((a, b) => b.length - a.length);

  for (const phrase of longPhrases) {
    const escaped = phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(escaped, 'g');
    result = result.replace(regex, GLOSSARY[phrase]);
  }

  // 再匹配单词
  const words = Object.keys(GLOSSARY)
    .filter(k => !k.includes(" ") && k.length > 1)
    .sort((a, b) => b.length - a.length);

  for (const word of words) {
    const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'g');
    result = result.replace(regex, GLOSSARY[word]);
  }

  return result;
}
